# Generated by Django 3.2 on 2021-11-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0017_bookturf_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='licence',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
