# Generated by Django 3.2 on 2021-12-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0018_turf_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='game',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='turf',
            name='video',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
