# Generated by Django 3.2 on 2021-12-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0019_auto_20211205_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
    ]
