# Generated by Django 3.2 on 2021-12-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0022_ownerreg_owner_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookturf',
            name='no_per',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
