# Generated by Django 3.2 on 2021-12-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0023_bookturf_no_per'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerreg',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userreg',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
