# Generated by Django 3.2 on 2021-12-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0024_auto_20211207_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookturf',
            name='end_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
