# Generated by Django 3.2 on 2021-12-09 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0026_turffeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='turffeedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Turf.userreg'),
        ),
    ]
