# Generated by Django 3.2.8 on 2021-12-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0027_turffeedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
